# Generated by Django 3.2.6 on 2022-08-15 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doeco_app', '0002_rename_user_post_post_writer_comment_comment_writer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='doeco_app/%Y/%m/', verbose_name='IMAGE'),
        ),
    ]
