# Generated by Django 4.1 on 2022-08-19 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doeco_app', '0002_freepost_freecomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='freepost',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='post_photo'),
        ),
    ]
