# Generated by Django 3.2.6 on 2022-08-15 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doeco_app', '0003_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/doeco_app/%Y/%m/', verbose_name='IMAGE'),
        ),
    ]
