# Generated by Django 4.1 on 2022-08-19 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doeco_app', '0004_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='doeco_app/%Y/%m/', verbose_name='IMAGE'),
        ),
    ]
